### ISSUE TITLE
Too-short password isn't too short

### ISSUE THREAD

**Issue by mdo5004** [learn-co-curriculum/devise_lab#30]
sign_up_spec.rb:39 
sign_up_with('test@example.com', 'please', 'please') signs up with a 6-letter password, which is not too short, according to Devise.

**Comment by BeejLuig** [comment]
@Lukeghenco: @Jdville03 found that the issue seems to stem from the fact that the auto-generated `devise.rb` file inside `config/initializers` _used to_ default to `8..72`, as it says in the [Devise docs](http://www.rubydoc.info/github/plataformatec/devise/master/Devise/Models/Validatable), but now the default value is `6..128`. 

Updating the spec to use a <=5 letter word may be the best solution. Otherwise, the readme could mention changing default values in the `devise.rb` file or adding something like `devise :database_authenticatable, :validatable, password_length: 7..128` in the application controller.

**Comment by chrissyhunt** [comment]
Ran into the same issue on this lab several months after these last comments. I shortened the test password to get the tests passing and submitted a pull request.
